#!/bin/bash

if [ ! $1 ]; then
  echo "Not enough arguments!"
  exit 1
fi

if [ $2 ]; then
  echo "Too many arguments!"
  exit 1
fi

rails new $1 -m https://github.com/blaix/rails-app-templates/raw/master/default.rb
